bank:  # specify full name to avoid ambiguity
    checkings: 'Activa:Huidige Activa:Lopende Rekening'
    savings: 'Activa:Huidige Activa:Spaarrekening'
locations:
    dir: 'Documents/Financien/'  # Relative to your home folder 
    book: 'practice.gnucash'  # relative to dir
    bank_statement: 'bank_statement.csv'  # relative to dir
read_only: false
